# notification daemon
exec-once = dunst

# authentication daemon
exec-once = systemctl --user start hyprpolkitagent

# hyprpaper
# exec-once = hyprpaper -c ~/.config/hypr/hyprpaper/hyprpaper.conf

# waybar
exec-once = waybar

# awww
exec-once = awww-daemon

# wootility-bg
exec-once = wooting-bg-service

# hypridle
# exec-once = hypridle
